version: "3.9"

services:
  db:
    image: postgres:14-alpine
    container_name: payment-service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment_service
    volumes:
      - payment_service_db:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql  # auto-load schema on first boot
    ports:
      - "5432:5432"
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - loki_data:/tmp/loki
      - ./loki-config.yaml:/etc/loki/config.yaml
    command: -config.file=/etc/loki/config.yaml

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
     - /var/log:/var/log
     - /var/lib/docker/containers:/var/lib/docker/containers:ro
     - ./promtail-config.yaml:/etc/promtail/config.yaml:ro
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
    - grafana_data:/var/lib/grafana
  

  rabbitmq:
    image: rabbitmq:3-management
    container_name: payment-service-rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:7-alpine
    container_name: payment-service-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  app:
    build: .
    container_name: payment-service
    depends_on:
      - db
      - rabbitmq
      - redis
    ports:
      - "8080:8080"
      - "9464"
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: payment_service
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
      RABBITMQ_QUEUE: payment_webhooks_queue
    volumes:
      - .:/app
    command: npm run dev

volumes:
  payment_service_db: {}
  rabbitmq_data: {}
  grafana_data: {}
  loki_data: {}
