services:
  db:
    image: postgres:14-alpine
    container_name: payment-service-db
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: payment_service
    volumes:
      - payment_service_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: payment-service-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:7-alpine
    container_name: payment-service-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
  
  app:
    build: .
    container_name: payment-service
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: your_db_user
      DB_PASSWORD: your_db_password
      DB_NAME: payment_service
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
      RABBITMQ_QUEUE: payment_webhooks_queue
    volumes:
      - .:/app
    command: npm run dev

volumes:
  payment_service_db:
  rabbitmq_data: