server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Docker containers auto-discovery
  - job_name: 'docker'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      # Capture container name
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      # Capture docker-compose service name
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service_name'
      # Only scrape containers in observability stack
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        regex: 'payment-service-production'
        action: keep

  # Payment service metrics
  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:8080']

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['payment-service-redis:6379']

  # RabbitMQ
  - job_name: 'rabbitmq'
    metrics_path: /api/metrics  # RabbitMQ exposes metrics via management plugin
    static_configs:
      - targets: ['payment-service-rabbitmq:15672']

  # Database (Postgres)
  - job_name: 'db'
    static_configs:
      - targets: ['payment-service-db:5432']
