# Global Prometheus settings
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alerting (optional)
alerting:
  alertmanagers: []

# Scrape configs for all services
scrape_configs:

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # Payment Service container (assuming /metrics endpoint)
  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:9464']  # Node exporter / app metrics port

  # Redis exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # RabbitMQ exporter
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq-exporter:9419']

  # PostgreSQL exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
